### ISSUE TITLE
[DOC] Control over the webUI only works within the ETH network

### ISSUE THREAD

**Issue by romain-jacob** [nsg-ethz/autopower#27] opened 2024-09-23 09:11 UTC
... at least it seems to be the case, though I don't know whether it's intentional. Might want to rethink this, and at least document it (if it's not already somewhere...)

**Comment by UsualSpec** [comment] 2024-09-23 09:30
No. This should definitely not be the case.

**Comment by UsualSpec** [comment] 2024-12-20 16:07
Closing as can't reproduce. Please reopen this issue if it still occurs.

**Closed as not planned by UsualSpec** 2024-12-20 16:07 UTC

**Comment by UsualSpec** [comment] 2025-02-17 10:20
Maybe re-signing certificates externally didn't work? I've changed the signCerts.sh script now to use the jump host.
